spring:
  application:
    name: companyhub

github:
  api:
    url: https://api.github.com
    token: token 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
  repo:
    owner: k5rv
    name: CompanyHub

companyhub:
  path: src/main/resources/companies.csv
  source: main
  target: target

logging:
  level:
    com.companyhub: INFO
